# Site settings
title: Computer Science for Undergraduates
email: mukeshpareek1997@gmail.com
description: A roadmap for the computer science undergraduates
baseurl: "/top-down"
url: "https://pareek210.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
